### ISSUE TITLE
ERB code highlighted

### ISSUE THREAD

**Issue by yonkeltron** [eschulte/rhtml#1]
All of the ERB in a file is highlighted in Emacs. Here is an example using the default test.rhtml file:

http://gyazo.com/421910730c668e9a5d007b05f2844d41.png

**Comment by eschulte** [comment]
it should be possible to change the font colour used for highlighting if it is offensive.  Sorry it took over a year to respond to this issue, I'm not longer actively maintaining this repository.

**Comment by yonkeltron** [comment]
Thanks. Any idea if there's continuing emacs support for erb templates somewhere out there?

**Comment by eschulte** [comment]
rhtml should be stable and I am certainly willing to apply patches.  The place to ask would be the Rails On Emacs emacs-on-rails@googlegroups.com mailing list, they should know what tools exist and be able to provide help for rhtml usage.

Hope this helps -- Eric
